name: Waka Readme

on:
    schedule:
        # Runs at 12am IST
        - cron: "30 18 * * *"
    workflow_dispatch:
jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: BeamKunGzMARK/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_TIMEZONE: "True"
                  SHOW_LANGUAGE: "True"
                  SHOW_OS: "True"
