name: Waka Readme

on:
    schedule:
        - cron: "* */3 * * *"
    workflow_dispatch:
jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_TIMEZONE: "True"
                  SHOW_LANGUAGE: "True"
                  SHOW_OS: "True"
                  SHOW_EDITORS: "True"
                  SHOW_TOTAL_CODE_TIME: "True"
                  IGNORED_REPOS: "BeamNawapat"
                  SYMBOL_VERSION: 3
